# #import os

# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart

# port = 587
# smtp_server = "smtp-relay.sendinblue.com"
# login = "thato.thupudi@umuzi.org" # paste your login generated by Mailtrap
# password = "f2xPBaWzCgG4VwTD" # paste your password generated by Mailtrap

# sender_email = "thato.thupudi@umuzi.org"
# receiver_email = "thatothupudi@gmail.com"

# message = MIMEMultipart("alternative")
# message["Subject"] = "multipart test"
# message["From"] = sender_email
# message["To"] = receiver_email
# # Write the plain text part
# text = """\ Hi, Check out the new post on the Mailtrap blog: SMTP Server for Testing: Cloud-based or Local? https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/ Feel free to let us know what content would be useful for you!"""

# # write the HTML part
# html = """\ <html> <body> <p>Hi,<br> Check out the new post on the Mailtrap blog:</p> <p><a href="https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server">SMTP Server for Testing: Cloud-based or Local?</a></p> <p> Feel free to <strong>let us</strong> know what content would be useful for you!</p> </body> </html> """

# # convert both parts to MIMEText objects and add them to the MIMEMultipart message
# part1 = MIMEText(text, "plain")
# part2 = MIMEText(html, "html")
# message.attach(part1)
# message.attach(part2)

# # send your email
# with smtplib.SMTP("thato.thupudi@umuzi.org", 587) as server:
#   server.login(login, password)
#   server.sendmail( sender_email, receiver_email, message.as_string() )

# print('Sent')

#----------------------
import os
import smtplib
from string import Template
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
MY_ADDRESS ='thato.thupudi@umuzi.org'
PASSWORD ='f2xPBaWzCgG4VwTD'
Email_To = 'thatothupudi@gmail.com'
def get_contacts(filename):
    """
    Return two lists names, emails containing names and email addresses
    read from a file specified by filename.
    """
    names = []
    emails = []
    with open(filename, mode='r', encoding='utf-8') as contacts_file:
        for a_contact in contacts_file:
            names.append(a_contact.split()[0])
            emails.append(a_contact.split()[1])
    return names, emails
def read_template(filename):
    """
    Returns a Template object comprising the contents of the
    file specified by filename.
    """
    with open(filename, 'r', encoding='utf-8') as template_file:
        template_file_content = template_file.read()
    return Template(template_file_content)
def main():
    names, emails = get_contacts('contactlist.txt') # read contacts
    message_template = read_template('message.txt')
    # set up the SMTP server
    s = smtplib.SMTP(host='smtp-relay.sendinblue.com', port=587)
    s.starttls()
    s.login(MY_ADDRESS, PASSWORD)
    # For each contact, send the email:
    for name, email in zip(names, emails):
        msg = MIMEMultipart()       # create a message
        # add in the actual person name to the message template
        message = message_template.substitute(PERSON_NAME=name.title())
        # Prints out the message body for our sake
        print(message)
        # setup the parameters of the message
        msg['From']=MY_ADDRESS
        msg['To']=email
        msg['Subject']="This is TEST"
        # add in the message body
        msg.attach(MIMEText(message, 'plain'))
        # send the message via the server set up earlier.
        s.send_message(msg)
        del msg
    # Terminate the SMTP session and close the connection
    s.quit()
if __name__ == '__main__':
    main()